plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

Style/Documentation:
  Enabled: false
