# frozen_string_literal: true

require_relative 'daily_tech_news/version'
require_relative 'daily_tech_news/config'
require_relative 'daily_tech_news/logger'
require_relative 'daily_tech_news/article'
require_relative 'daily_tech_news/summarized_article'
require_relative 'daily_tech_news/deduplicator'
require_relative 'daily_tech_news/http_client'
require_relative 'daily_tech_news/sources/base'
require_relative 'daily_tech_news/sources/qiita'
require_relative 'daily_tech_news/sources/zenn'
require_relative 'daily_tech_news/sources/hacker_news'
require_relative 'daily_tech_news/sources/anthropic_blog'
require_relative 'daily_tech_news/claude_client'
